### ISSUE TITLE
stac-to-dc \ --catalog-href='https://earth-search.aws.element84.com/v0/' \ --bbox='25,20,35,30' \ --collections='sentinel-s2-l2a-cogs' \ --datetime='2020-01-01/2020-03-31'...running this command gives exception

### ISSUE THREAD

**Issue by chiranjivSharma** [opendatacube/datacube-dataset-config#41]
stac-to-dc \
--catalog-href='https://earth-search.aws.element84.com/v0/' \
--bbox='25,20,35,30' \
--collections='sentinel-s2-l2a-cogs' \
--datetime='2020-01-01/2020-03-31'

I am running this command for indexing.But I get below mentioned output-

stac-to-dc --catalog-href='https://earth-search.aws.element84.com/v0/' --bbox='25,20,35,30' --collections='sentinel-s2-l2a-cogs' --datetime='2020-01-01/2020-03-31'
/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/pystac_client/client.py:186: NoConformsTo: Server does not advertise any conformance classes.
  warnings.warn(NoConformsTo())
Traceback (most recent call last):
  File "/home/bel/miniconda3/envs/cubeenv1/bin/stac-to-dc", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/odc/apps/dc_tools/stac_api_to_dc.py", line 302, in cli
    added, failed, skipped = stac_api_to_odc(
                             ^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/odc/apps/dc_tools/stac_api_to_dc.py", line 159, in stac_api_to_odc
    search = client.search(**config)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bel/miniconda3/envs/cubeenv1/lib/python3.11/site-packages/pystac_client/client.py", line 591, in search
    raise DoesNotConformTo(
pystac_client.warnings.DoesNotConformTo: Server does not conform to ITEM_SEARCH, There is not fallback option available for search.

**Comment by mehran66** [comment]
it seems that stack api has changed...this works for me.

stac-to-dc \
--catalog-href='https://earth-search.aws.element84.com/v1/' \
--bbox='25,20,35,30' \
--collections='sentinel-2-l2a' \
--datetime='2020-01-01/2020-03-31'
